### ISSUE TITLE
Does not contain a method 'propertyOrParam'

### ISSUE THREAD

**Issue by tjaynl** [SaifurRahmanMohsin/magnificgallery-plugin#1]
After installing and including this plugin i get the following error:

An exception has been thrown during the rendering of a template ("The component 'Mohsin\MagnificGallery\Components\Magnific' does not contain a method 'propertyOrParam'.").

**Comment by mohsin** [comment]
This is an [old issue](http://octobercms.com/forum/post/the-component-mohsinmagnificgallerycomponentsmagnific-does-not-contain-a-method-propertyorparam) which has been resolved when OctoberCMS switched to RC. I believe you are using the old beta version. Kindly update your OctoberCMS (force update from backend) and let me know if that solves the issue.
