### ISSUE TITLE
Alt and title tags for images

### ISSUE THREAD

**Issue by noobiemania** [SaifurRahmanMohsin/magnificgallery-plugin#2]
As per subject, I would request the images to have those tags so as to improve SEO.

**Comment by mohsin** [comment]
What sort of tags? Could you explain or show a sample and I’ll consider adding that as an optional feature perhaps.

**Comment by noobiemania** [comment]
example: alt="alt_tag", title="title_tag".
Please add these options to the backend so admin can edit.

**Comment by mohsin** [comment]
Ah that’s what I thought you wanted. Alright I’ll see what can be done. Thanks for the enhancement request.

**Comment by mohsin** [comment]
I’m a little engrossed with work so this might take a while. Meanwhile I suggest that you type in this alt tag as description for image and title tag as title for image and then [override the partial](https://octobercms.com/docs/cms/components#overriding-partials) to achieve this.

```
<div id="{{ __SELF__ }}" class="magnific">
  {% for i, image in gallery.images %}
  <a href="{{ image.path }}" desc="{{ image.description }}" title="{{ image.title }}"><img alt=“{{ image.description}}” title=“{{ image.title }}” src="{{ gallery.images[i].thumb( width , height ) }}" width="{{ width }}" height="{{ height }}"></a>
  {% endfor %}
</div>
```

**Comment by noobiemania** [comment]
thanks
