### ISSUE TITLE
Opening Component

### ISSUE THREAD

**Issue by marcoelho97** [SaifurRahmanMohsin/magnificgallery-plugin#5]
Hello @SaifurRahmanMohsin ,

In both builds 350 and 351, and I can't open the component. This is what shows up:
![image](https://cloud.githubusercontent.com/assets/13586621/17548367/869a96dc-5ee3-11e6-8ece-6d3a2c984bba.png)

Hope you can fix it as soon as possible!! Thank you!

**Comment by marcoelho97** [comment]
@SaifurRahmanMohsin I have found the problem.
Go "Components\magnific.php", line 67
From: protected function getidGalleryOptions()
To:      public function getidGalleryOptions()

**Comment by mohsin** [comment]
Thank you for finding the issue. I'll fix it in a couple of minutes. If you'd like, then make a pull request, and I'll merge that instantly.
