### ISSUE TITLE
How can i get list of galleries?

### ISSUE THREAD

**Issue by raakesh** [SaifurRahmanMohsin/magnificgallery-plugin#6]
Is there any way to get list of all galleries?

**Comment by mohsin** [comment]
Yeah you can…
1. Create a new page from the CMS tab. Now under **Markup** put

```
{% for gallery in galleries %}
    <li>#{{gallery.id}} - {{ gallery.name }} (No. of images: {{ gallery.images|length }})</li>
{% else %}
    <li>No galleries available</li>
{% endfor %}
```

And under **Code** put

```
function onStart()
{
    $galleries = new \Mohsin\MagnificGallery\Models\Gallery;
    $this['galleries'] = $galleries -> all();
}
```

No need to include any component, this directly tells the system to create a Gallery Model’s instance. So, you can use this to show a list of galleries if you need. Although, this isn’t really what the plugin was designed for. Let me know if you have any other queries. I’m closing this now.
