### ISSUE TITLE
Question about hover on image when extending component

### ISSUE THREAD

**Issue by Hessel91** [SaifurRahmanMohsin/magnificgallery-plugin#8]
Hi, I would like to add a hover effect with button to expand when hovering on the image. 
But when I overwrite the component with my own partial I can't manage to get It done. 
do you have an idea how I can do this?
Kind regards!

**Comment by mohsin** [comment]
Whoops, sorry I missed your question. I guess you have found the solution by now considering ample time has passed. If not, please read [OctoberCMS' documentation on overriding partials](https://octobercms.com/docs/cms/components#overriding-partials).
