### ISSUE TITLE
Thumbnail component

### ISSUE THREAD

**Issue by mkinternet** [SaifurRahmanMohsin/magnificgallery-plugin#9]
Component doesn't crop images

There is:
`<img title="{{ image.title }}" alt="{{ image.description }}" src="{{ image.thumb( width , height ) }}" width="{{ magnific.property('width') }}" height="{{ magnific.property('height') }}">`

It should be
`<img title="{{ image.title }}" alt="{{ image.description }}" src="{{ image.thumb( magnific.property('width') , magnific.property('height') ) }}" width="{{ magnific.property('width') }}" height="{{ magnific.property('height') }}">`

**Comment by mohsin** [comment]
Thanks for pointing this out. Will fix.
